function add_page(){
    auth('prodadmin@test.com', add_page_secured,'/login')
    //add_page_secured()
}
let glImageFile2Add; //File selected by imageButton
let randNumber = Math.floor(100000 + Math.random() * 900000);
function add_page_secured(){
    //-------------------------------------------------------------------------------------------
    //Auto generate prodID for a new add-in product
    //Count total products in firebase
    var snapshot;
    var nextID;
    try{
    
    snapshot = firebase.firestore().collection(COLLECTION).get().then(snap => {
        size = snap.size // will return the collection size

        //----
        //CHECK TOTAL NUMBER OF PRODUCTS IN DATABASE
        products = []   //array of products
        const snapshot = firebase.firestore().collection(COLLECTION)
        .get()
        .then(function(snapshot){
            snapshot.forEach(doc =>{
                const{prodID,name,summary,price,image,image_url} = doc.data()
                const p = {docId: doc.id,prodID,name,summary,price, image,image_url}
                products.push(p)

            }); 
            console.log("Total products:" + products.length)
             //MAKE SURE THE PRODUCTID IS UNIQUE
        
        nextID = size+1;
        console.log("await 1....")   
        var i=0;
        for(var i=0;i<products.length;i++){
            if(nextID==products[i].prodID) 
                {
                    console.log("id matched")
                    nextID=nextID+1;
                    console.log("New nextID: "+nextID)
                }
            //console.log(products[i].prodID)
        }
        console.log("await 2....") 
        console.log(nextID)
        
        glPageContent.innerHTML = '<h1>Add Page</h1>'
        glPageContent.innerHTML+=`
        <div class = "form-group">
    ProdID: <input class="form-control" type="text" id="prodID" value=${nextID} readonly />
   
    </div>
    
     <div class = "form-group">
        Name: <input class="form-control" type="text" id="name" />
        <p id="name_error" style="color:red;" />
    </div>


    <div class="form-group">
        Summary:<br>
        <textarea class="form-control" id="summary" cols="40" rows="5"></textarea>
        <p id="summary_error" style="color:red;" />
    </div>

    <div class="form-group">
        Price:<input class="form-control" type="text" id="price" />
        <p id="price_error" style="color:red;" />
    </div>

    <div class = "form-group">
        Image: <input type="file" id="imageButton" value="upload" />
        <p id="image_error" style="color:red;" />
    </div>

    <button class="btn btn-primary" type="button" onclick="addProduct(${nextID})">Add</button>
    
    `;
    const imageButton  = document.getElementById('imageButton')
    imageButton.addEventListener('change', e => {
        glImageFile2Add = e.target.files[0]
        //console.log('file upload', e.target.files[0])
    })
     });
        
    });

       
      
        
        
       
       
}catch(e){
    glPageContent.innerHTML='Forestore access error. Try again!!!!' + e
            return

}
    
    
}

async function addProduct(nextID){
    const name = document.getElementById('name').value
    const summary = document.getElementById('summary').value
    let price = document.getElementById('price').value
    //*****NOTE: prodID is autogenerated */
    prodID=document.getElementById('prodID').value

    //validate input
    const nameErrorTag = document.getElementById('name_error')
    const summaryErrorTag = document.getElementById('summary_error')
    const priceErrorTag = document.getElementById('price_error')
    const imageErrorTag = document.getElementById('image_error')


    nameErrorTag.innerHTML = validate_name(name)
    summaryErrorTag.innerHTML = validate_summary(summary)
    priceErrorTag.innerHTML = validate_price(price)
    imageErrorTag.innerHTML = !glImageFile2Add ? 'Error: image file not selected' : null

    if(nameErrorTag.innerHTML || summaryErrorTag.innerHTML || priceErrorTag.innerHTML || imageErrorTag.innerHTML)
        return
 
//ADD PRODUCT INTO FIREBASE
//--- Upload Image ---

 try{
     var products=[];
     const image  = Date.now() + glImageFile2Add.name    //unique name
    
      
     
     let prodID = nextID
     const ref = firebase.storage().ref(IMAGE_FOLDER + image)
     const taskSnapshot = await ref.put(glImageFile2Add)
     const image_url = await taskSnapshot.ref.getDownloadURL()


    // product: name, summary, price in Firestore
    price = Number(price)    //convert price to number and store
    await firebase.firestore().collection(COLLECTION).doc()
        .set({prodID,name, summary, price, image, image_url})


     //console.log('image_url', image_url)   //for testing

     glPageContent.innerHTML=`
     <h1>${name} is added</h1>
     <a href="/show" class="btn btn-outline-primary">Show All</a>
     `;
 } catch (e){
     glPageContent.innerHTML=`
     <h1>Cannot add a product</h1>
     ${JSON.stringify(e)}
     `;

 }


}